version: "3.8"

services:

  mysql-question:
    container_name: mysql-question
    image: mysql:8.0.35
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: question-service
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./docker-volumes/mysql-question:/var/lib/mysql
    restart: always

  mysql-gateway:
    container_name: mysql-gateway
    image: mysql:8.0.35
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gateway-service
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./docker-volumes/mysql-gateway:/var/lib/mysql
    restart: always

  mysql-leaderboard:
    container_name: mysql-leaderboard
    image: mysql:8.0.35
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leaderboard-service
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./docker-volumes/mysql-leaderboard:/var/lib/mysql
    restart: always

  question-service:
    container_name: question-service
    build:
      context: ./question-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-question:3306/question-service
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka
    depends_on:
      - mysql-question
      - discovery-service
    restart: always

  discovery-service:
    container_name: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.29-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"


#  question-service:
#    build:
#      context: ./question-service
#      dockerfile: Dockerfile
#    ports:
#      - "0:8080"
#    environment:
#      - spring.datasource.url=jdbc:mysql://mysql-question:3306/question-service
#      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka
#    depends_on:
#      - mysql-question
#      - discovery-service
#    restart: always
#    deploy:
#      mode: replicated
#      replicas: 2